version: '3.1'
services:
  stats-server:
    build: ./stats-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - ewm-service
    environment:
      - STATS_SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
  ewm-service:
    image: postgres:14-alpine
    container_name: ewm-service
    ports:
      - "6541:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
