version: '3.1'
services:
  stats-server:
    build: ./stats-server
    image: stats_image
    container_name: explore_stats_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - ewm-service
    environment:
      - STATS_SERVER_PORT=9090
      - DB_HOST=explore_stats_db
      - DB_PORT=5432
      - DB_NAME=explore_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    image: postgres:14-alpine
    container_name: ewm-service
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root